## Comparing performance with the lists

In [14]:
import numpy as np

In [11]:
%%time
N = 10**8
list_ = list(range(N))

for i in range(N):
	list_[i] = list_[i]*list_[i]

CPU times: user 13.2 s, sys: 5.32 s, total: 18.6 s
Wall time: 18.5 s


In [5]:
%%time
list_ = list(range(N))
list_ = [item*item for item in list_]

CPU times: user 4.96 s, sys: 2.89 s, total: 7.85 s
Wall time: 7.81 s


In [7]:
%%time
# using map function call
list_ = list(range(N))
list_ = map(lambda x: x*x, list_)

CPU times: user 1.37 s, sys: 1.6 s, total: 2.97 s
Wall time: 2.93 s


In [8]:
%%time

list_ = list(range(N))

list_sum = 0
for item in list_:
	list_sum += item

CPU times: user 8.68 s, sys: 1.62 s, total: 10.3 s
Wall time: 10.3 s


In [9]:
%%time
list_ = list(range(N))

list_sum = sum(list_)

CPU times: user 1.75 s, sys: 1.54 s, total: 3.29 s
Wall time: 3.25 s


## Numpy arrays

In [15]:
import numpy as np

In [12]:
%time
arr = np.arange(N)
arr = arr * arr



CPU times: user 10 µs, sys: 5 µs, total: 15 µs
Wall time: 28.8 µs


In [13]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 88.3 ms, sys: 248 ms, total: 337 ms
Wall time: 334 ms


## Numpy arrays

## Creating numpy arrays

In [19]:
import numpy as np

arr = np.arange(5)
print(arr, type(arr))


[0 1 2 3 4] <class 'numpy.ndarray'>


In [20]:
arr = np.array([1,2,3,4])
print(arr, type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [25]:
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)   # Number of bytes

int64
1
(4,)
4
8


In [26]:
arr = np.array([1,2,3.0,4])
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)   # Number of bytes


float64
1
(4,)
4
8


### 2D arrays

In [27]:
arr2d = np.array([
	              [1,2,3],
				  [4,5,6]
])

In [28]:
print(arr2d)
print(arr2d.dtype)
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.size)
print(arr2d.itemsize)   # Number of bytes

[[1 2 3]
 [4 5 6]]
int64
2
(2, 3)
6
8


In [29]:
arr3d = np.array([
	         [
				[1,2,3],
				[4,5,6]
			 ],
			 [
				[7,8,9],
				[10,11,12]
			 ]
])

In [30]:
print(arr3d)
print(arr3d.dtype)
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.size)
print(arr3d.itemsize)   # Number of bytes

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
int64
3
(2, 2, 3)
12
8


In [32]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [33]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [35]:
np.random.randn(2,3)

array([[ 0.03718594, -0.04410957,  0.53743246],
       [-1.14412974,  1.62908007,  0.90742447]])

In [36]:
np.random.rand(2,3)

array([[0.96573847, 0.5759794 , 0.24476366],
       [0.0221254 , 0.82674779, 0.17153199]])

In [37]:
np.random.randint(0,100,(2,3))

array([[48, 54,  6],
       [ 7, 65, 92]])

In [38]:
np.arange(7,71,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [39]:
np.linspace(7,70,10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [40]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

## Indexing Arrays

In [41]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr3d[0,0,0]

1

In [44]:
arr3d[0,:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr3d[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [47]:
arr3d[:,:,0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [48]:
# Looking for even number

arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [50]:
# Observations. It is a one 1D array
arr3d[arr3d % 2 ==0]

array([ 2,  4,  6,  8, 10, 12])

In [52]:

arr3d[(arr3d % 2 ==1) & (arr3d >3)]

array([ 5,  7,  9, 11])

In [53]:
arr_slice = arr3d[:,:,0:2]

In [54]:
arr_slice[0,0,1]

2

In [55]:
arr_slice[0,0,0] = 1729

In [56]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [57]:
arr3d
# Observations: Array slice is also changed. Good point to note.
#Reference is only changed

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [58]:
arr_slice = np.copy(arr3d[:,:,0:2])

In [59]:
arr_slice[0,0,0] = 1

In [60]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [61]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

## Operations on Numpy

In [4]:
import numpy as np
arr1 = np.random.randn(2,3)
arr2 = np.random.randn(2,3)

In [5]:
arr1

array([[-0.17119503, -1.47764693, -0.12152692],
       [ 0.50371587,  1.83341084, -0.10836141]])

In [6]:
arr2

array([[-0.15710587,  1.21275106, -0.1623603 ],
       [-1.4953953 , -0.27579742,  0.04603795]])

In [7]:
arr1+arr2

array([[-0.3283009 , -0.26489587, -0.28388723],
       [-0.99167943,  1.55761342, -0.06232346]])

In [8]:
np.exp(arr1)

array([[0.84265721, 0.22817397, 0.88556721],
       [1.6548591 , 6.25518573, 0.89730324]])

In [9]:
np.log(arr1)

/tmp/ipykernel_458331/2108464003.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr1)


array([[        nan,         nan,         nan],
       [-0.68574292,  0.60617808,         nan]])

## Find the area of square which is not on quadrant

In [23]:
ndim = 2
npoints = 10**6
points = np.random.rand(npoints, ndim)

In [24]:
points[0:2,:]


array([[0.50536029, 0.27211025],
       [0.04055697, 0.73495756]])

In [25]:
%%time
dfo = np.zeros((npoints,1))
outside_points = 0

for i in range(npoints):
	for j in range(ndim):
		dfo[i] += points[i,j]**2

	dfo[i] = np.sqrt(dfo[i])
	if dfo[i] > 1:
		outside_points += 1

CPU times: user 8.59 s, sys: 1.39 s, total: 9.98 s
Wall time: 8.22 s


In [27]:
%time
# efficient version
sqr_points = points * points
dfo = np.sqrt(np.sum(sqr_points,axis=1))
outside_points = np.sum(dfo >1)

CPU times: user 14 µs, sys: 1 µs, total: 15 µs
Wall time: 30 µs


In [28]:
outside_points/npoints

0.214749

## Broadcasting

In [29]:
arr1 = np.arange(6)

In [30]:
arr1.shape

(6,)

In [39]:
arr1 = arr1.reshape(3,2)

In [40]:
arr2 = arr1.reshape(3,2)

In [41]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [42]:
arr1+arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [45]:
arr2[0].reshape(1,2)

array([[0, 1]])