# Recitation 0B - Fundamentals of NumPy
## Table of Contents
1. What is NumPy?
2. Installation
3. Initialization
4. Accessing
5. Modifying data
6. Pivoting data
7. Combining data
8. Math operations

## 1. What is NumPy?

NumPy is the fundamental package for scientific computing in Python. 
It is a Python library that provides and an assortment of operations for fast operations on arrays - from mathematical, logical operations to basic linear algebra, random simulation and much more.

## 2. Installation
Generally NumPy is pre-installed on CoLab/AWS. You should first check if NumPy is available and its version.

To manually install Numpy, please follow the instructions below.

In [1]:
# Check the installation of NumPy
!pip show numpy

# Install NumPy
!pip install numpy

# Import NumPy 
import numpy as np

Name: numpy
Version: 1.17.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: 


## 3. Initialization

### a. Intrinsic NumPy array creation functions


#### 1D array creation functions

In [ ]:
# return evenly spaced values within a given interval
range_arr = np.arange(10)
print("An array given range is \n", range_arr, " with dimensions ", range_arr.shape, "\n")

# return evenly spaced numbers over a specified interval
linspace_arr = np.linspace(2.0, 3.0, num=5, endpoint=False)
print("An evenly spaced array given range is \n", linspace_arr, " with dimensions ", linspace_arr.shape, "\n")

In [3]:
range_arr = np.arange(10)
print("An array given range is \n", range_arr, "with dimensions ", range_arr.shape,"\n")

# return evenly spaces over a given interval
linspace_arr = np.linspace(2.0,3.0,num=5, endpoint=False)
print("An evenly spaced array given range is \n", linspace_arr, " with dimensions ", linspace_arr.shape, "\n")


linspace_arr = np.linspace(2.0,3.0,num=5, endpoint=True)
print("An evenly spaced array given range is \n", linspace_arr, " with dimensions ", linspace_arr.shape, "\n")

An array given range is 
 [0 1 2 3 4 5 6 7 8 9] with dimensions  (10,) 

An evenly spaced array given range is 
 [2.  2.2 2.4 2.6 2.8]  with dimensions  (5,) 

An evenly spaced array given range is 
 [2.   2.25 2.5  2.75 3.  ]  with dimensions  (5,) 



#### General ndarray creation functions

In [ ]:
# initialize an empty array with size 2 x 2
empty_arr = np.empty((2, 2))
print("An empty array is \n", empty_arr, " with dimensions ", empty_arr.shape, "\n")

# initialize an all zero array with size 2 x 3
zeros_arr = np.zeros((2, 3))
print("A zeros array is \n", zeros_arr, " with dimensions ", zeros_arr.shape, "\n")

# initialize an all one array with size 4 x 2
ones_arr = np.ones((4, 2))
print("A ones array is \n", ones_arr, " with dimensions ", ones_arr.shape, "\n")

In [4]:
empty_arr = np.empty((2,2))
print("An empty array is \n", empty_arr, "with dimensions ", empty_arr.shape, "\n")

zeros_arr = np.zeros((2,3))
print("A zeros array is \n", zeros_arr, " with dimensions ", zeros_arr.shape, "\n")

ones_arr = np.ones((4,2))
print("A ones array is \n", ones_arr, " with dimensions ", ones_arr.shape, "\n")

An empty array is 
 [[1.59209690e-316 0.00000000e+000]
 [1.58101007e-322 6.90012435e-310]] with dimensions  (2, 2) 

A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]]  with dimensions  (2, 3) 

A ones array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  with dimensions  (4, 2) 



In [5]:
zeros_like_arr = np.zeros_like(ones_arr)

ones_like_arr = np.ones_like(zeros_arr)

In [6]:
# return an array of zeros with the same shape and type as a given array
zeros_like_arr = np.zeros_like(ones_arr)
print("A zero like array is \n", zeros_like_arr, " with dimensions ", zeros_like_arr.shape, "\n")

# return an array of ones with the same shape and type as a given array
ones_like_arr = np.ones_like(zeros_arr)
print("A ones like array is \n", ones_like_arr, " with dimensions ", ones_like_arr.shape, "\n")

A zero like array is 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]  with dimensions  (4, 2) 

A ones like array is 
 [[1. 1. 1.]
 [1. 1. 1.]]  with dimensions  (2, 3) 



In [7]:
tens_arr = np.full((2,2),10)
full_like_arr = np.full_like(zeros_arr,0.1,dtype=np.double)

In [8]:
# return a new array of given shape and type, filled with fill_value
tens_arr = np.full((2,2), 10)
print("A filled array is \n", tens_arr, " with dimensions ", tens_arr.shape, "\n")

# Return a full array with the same shape and type as a given array.
full_like_arr = np.full_like(zeros_arr, 0.1, dtype=np.double)
print("A full like array is \n", full_like_arr, " with dimensions ", full_like_arr.shape, "\n")

A filled array is 
 [[10 10]
 [10 10]]  with dimensions  (2, 2) 

A full like array is 
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]  with dimensions  (2, 3) 



### b. Create an array from existing data

#### Conversion from other Python structures (i.e. lists and tuples)

In [9]:
new_list = [1,2,3,4]
arr_from_list = np.array(new_list)

In [10]:
# initialize an array with the given list
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("An array from given list is \n", arr_from_list, " with dimensions ", arr_from_list.shape, "\n")

An array from given list is 
 [1 2 3 4]  with dimensions  (4,) 



#### Reading arrays from disk

In [ ]:
# initialize an array by loading data from a txt file
#txt_arr = np.loadtxt(path_to_txt_file)

# initialize an array by loading data from a npy file
#loaded_arr = np.load(path_to_npy_file)

### c. Use of special library functions (e.g., random)

In [15]:
a = np.random.randint(0,10,size=(1,4))
print("Random integer array", a, "of shape ", a.shape)

np.random.seed(0)
a = np.random.randint(0,10,size=(1,4))
print("Random integer array with seed", a, "of shape ", a.shape)

Random integer array [[7 9 3 5]] of shape  (1, 4)
Random integer array with seed [[5 0 3 3]] of shape  (1, 4)


In [ ]:
a = np.random.randint(0, 10, size = (1,4))
print("Random integer array", a, "of shape ", a.shape)

np.random.seed(0)
a = np.random.randint(0, 10, size = (1,4))
print("Random integer array with seed", a, "of shape ", a.shape)

In [17]:
# create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
uniform_rand_arr = np.random.rand(3,2)
print("A random array from a uniform distribution is \n", uniform_rand_arr, " with dimensions ", uniform_rand_arr.shape, "\n")

# For random samples from N(\mu, \sigma^2), use:
# sigma * np.random.randn(...) + mu
mu = 3
sigma =2.5
sample_normal_arr = mu + sigma * np.random.randn(2, 4)
print("A random array from a gaussian distribution is \n", sample_normal_arr)
print("with mu: ", mu)
print("with sigma: ", sigma)
print("with dimensions ", sample_normal_arr.shape)

A random array from a uniform distribution is 
 [[0.95715516 0.14035078]
 [0.87008726 0.47360805]
 [0.80091075 0.52047748]]  with dimensions  (3, 2) 

A random array from a gaussian distribution is 
 [[ 5.92068284  5.36796487  5.71371759  8.95556112]
 [ 1.98494066  3.66611335 -0.38928431  2.71474367]]
with mu:  3
with sigma:  2.5
with dimensions  (2, 4)


## 4. Accessing data

### a. Indexing: Accessing values from Numpy Arrays

In [20]:
n = np.random.rand(4,5,6) # see this as 4 batches, each containing 5 rows and 6 columns

n[1,2,3]

0.7521345209879338

In [21]:
n = np.random.rand(4, 5, 6) # see this as 4 batches, each containing 5 rows and 6 columns
n

n[1, 2, 3] # returns the element located in the fourth column of third row of the second batch.

0.42783437883147235

### b. Slicing: Accessing subsections of Numpy Arrays based on Indices

In [22]:
print(n[0,:,:])

print(n[0,0:3,0:4])

print(n[:,3,4])

[[0.44737829 0.72769634 0.74223798 0.30698606 0.11977135 0.44387868]
 [0.39177432 0.53184918 0.84535768 0.53627454 0.68027015 0.60917758]
 [0.098478   0.09202759 0.05596583 0.08653249 0.23717329 0.83951297]
 [0.52237053 0.51307486 0.64983197 0.54459088 0.0324653  0.58015172]
 [0.77108905 0.37622657 0.49102474 0.98163968 0.24465141 0.3743232 ]]
[[0.44737829 0.72769634 0.74223798 0.30698606]
 [0.39177432 0.53184918 0.84535768 0.53627454]
 [0.098478   0.09202759 0.05596583 0.08653249]]
[0.0324653  0.73868266 0.51964283 0.62563662]


In [23]:
# slice along a batch
print(n[0, :, :]) # same as: n[0]

print(n[0, 0:3, 0:4])

# slice along multiple batches
print(n[:, 3, 4]) # returns the elements in the 4th row and 5th column across all batches

[[0.44737829 0.72769634 0.74223798 0.30698606 0.11977135 0.44387868]
 [0.39177432 0.53184918 0.84535768 0.53627454 0.68027015 0.60917758]
 [0.098478   0.09202759 0.05596583 0.08653249 0.23717329 0.83951297]
 [0.52237053 0.51307486 0.64983197 0.54459088 0.0324653  0.58015172]
 [0.77108905 0.37622657 0.49102474 0.98163968 0.24465141 0.3743232 ]]
[[0.44737829 0.72769634 0.74223798 0.30698606]
 [0.39177432 0.53184918 0.84535768 0.53627454]
 [0.098478   0.09202759 0.05596583 0.08653249]]
[0.0324653  0.73868266 0.51964283 0.62563662]


In [25]:
print(n[0::2])
print(n[0::2, 1:4, 1::2])

[[[0.44737829 0.72769634 0.74223798 0.30698606 0.11977135 0.44387868]
  [0.39177432 0.53184918 0.84535768 0.53627454 0.68027015 0.60917758]
  [0.098478   0.09202759 0.05596583 0.08653249 0.23717329 0.83951297]
  [0.52237053 0.51307486 0.64983197 0.54459088 0.0324653  0.58015172]
  [0.77108905 0.37622657 0.49102474 0.98163968 0.24465141 0.3743232 ]]

 [[0.24154569 0.22826361 0.48950933 0.89152268 0.35810748 0.38523742]
  [0.91672702 0.11381664 0.63112554 0.132815   0.37424458 0.32440486]
  [0.68011554 0.79553475 0.50393361 0.29624239 0.88596227 0.35187056]
  [0.73839034 0.55536126 0.20151771 0.5485191  0.51964283 0.34878266]
  [0.02461996 0.1488293  0.13185204 0.70791746 0.70907211 0.61174841]]]
[[[0.53184918 0.53627454 0.60917758]
  [0.09202759 0.08653249 0.83951297]
  [0.51307486 0.54459088 0.58015172]]

 [[0.11381664 0.132815   0.32440486]
  [0.79553475 0.29624239 0.35187056]
  [0.55536126 0.5485191  0.34878266]]]


In [26]:
#syntax for slicing at interval is start:stop:step_size 

print(n[0::2]) # slices from index 0 to the end of the dimension at intervals of 2

print(n[0::2, 1:4, 1::2]) # rows (2-5) and columns at an interval of 2, starting from 1

[[[0.44737829 0.72769634 0.74223798 0.30698606 0.11977135 0.44387868]
  [0.39177432 0.53184918 0.84535768 0.53627454 0.68027015 0.60917758]
  [0.098478   0.09202759 0.05596583 0.08653249 0.23717329 0.83951297]
  [0.52237053 0.51307486 0.64983197 0.54459088 0.0324653  0.58015172]
  [0.77108905 0.37622657 0.49102474 0.98163968 0.24465141 0.3743232 ]]

 [[0.24154569 0.22826361 0.48950933 0.89152268 0.35810748 0.38523742]
  [0.91672702 0.11381664 0.63112554 0.132815   0.37424458 0.32440486]
  [0.68011554 0.79553475 0.50393361 0.29624239 0.88596227 0.35187056]
  [0.73839034 0.55536126 0.20151771 0.5485191  0.51964283 0.34878266]
  [0.02461996 0.1488293  0.13185204 0.70791746 0.70907211 0.61174841]]]
[[[0.53184918 0.53627454 0.60917758]
  [0.09202759 0.08653249 0.83951297]
  [0.51307486 0.54459088 0.58015172]]

 [[0.11381664 0.132815   0.32440486]
  [0.79553475 0.29624239 0.35187056]
  [0.55536126 0.5485191  0.34878266]]]


## 5. Modifying data

### Modify single values

In [28]:
n_copy = np.copy(n)
print(n_copy[2,4,1] == n[2,4,1])

n_copy[2,4,1] = 0.005

# check if values in the two arrays are the same after copy
print(n_copy[2, 4, 1] == n[2, 4, 1])


True
False


In [29]:
n_copy = n
print(n_copy[2,4,1] == n[2,4,1])

n_copy[2,4,1] = 0.005

# check if values in the two arrays are the same after copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

True
True


In [30]:
#When you assign an array or its elements to a new variable, 
#you have to explicitly numpy.copy the array, otherwise the variable is a view into the original array.

n_copy = np.copy(n)

# check if values in the two arrays are the same before copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

n_copy[2, 4, 1] = 0.005

# check if values in the two arrays are the same after copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

True
True


### Modifying multiple values

In [31]:
# check if values in the two arrays are the same before copy
print(f"Are the arrays the same before modification: {n_copy[2, 3] == n[2, 3]}")
print(f"Before modifying values: {n_copy[2, 3]}")

n_copy[2, 3] = 0.5

print(f"After modifying values: {n_copy[2, 3]}")

# check if values in the two arrays are the same after copy
print(f"Are the arrays the same after modification: {n_copy[2, 3] == n[2, 3]}")

Are the arrays the same before modification: [ True  True  True  True  True  True]
Before modifying values: [0.73839034 0.55536126 0.20151771 0.5485191  0.51964283 0.34878266]
After modifying values: [0.5 0.5 0.5 0.5 0.5 0.5]
Are the arrays the same after modification: [False False False False False False]


## 6.Pivoting data

### a. Reshaping Arrays
Array reshaping is an operation that changes the shape of an array whilst maintaining the same data in the array. 

For instance, reshaping from (3, 4, 5) -> (2, 5, 6) or from (3, 4, 5) -> (6, 10). A reshape operation is valid, so long as the product of the new shape specified matches the product of the old shape.

#### Reshaping within the same number of dimensions

In [32]:
s = np.random.rand(3,4,5)
print(f"Original Shape: {s.shape}")

s.size

print(s)

Original Shape: (3, 4, 5)
[[[0.51062891 0.38682715 0.53008894 0.94470748 0.89286225]
  [0.6771144  0.63902738 0.54836134 0.27268312 0.14826864]
  [0.85630298 0.6350568  0.29964349 0.46021971 0.0245274 ]
  [0.5580651  0.36115152 0.50270954 0.15362754 0.42550764]]

 [[0.90617184 0.00851159 0.9688641  0.69089373 0.09941639]
  [0.28977588 0.53907355 0.72414785 0.38886743 0.22708397]
  [0.45485988 0.97208251 0.83381823 0.91479066 0.66728484]
  [0.44066609 0.68509199 0.64859831 0.02910001 0.91953144]]

 [[0.542457   0.99114165 0.38310289 0.80666933 0.46100683]
  [0.82682421 0.53911823 0.88726484 0.88010686 0.32830331]
  [0.40442494 0.54464736 0.6216929  0.37935608 0.54212945]
  [0.12091936 0.68069724 0.28711926 0.04297641 0.11609834]]]


In [33]:
s = np.random.rand(3, 4, 5)
print(f"Original Shape: {s.shape}")

s.size

print(s)

Original Shape: (3, 4, 5)
[[[0.10642941 0.31648792 0.24653479 0.56278312 0.90635423]
  [0.58010691 0.59793673 0.23804352 0.58088727 0.14587015]
  [0.33563098 0.62552797 0.36130568 0.91099399 0.87849262]
  [0.43415558 0.5176121  0.47466799 0.1843626  0.43476064]]

 [[0.18755194 0.71520783 0.52300639 0.32056533 0.00309954]
  [0.59730294 0.64907833 0.00518963 0.9702218  0.66386607]
  [0.2931444  0.20036432 0.92570215 0.30925129 0.40321803]
  [0.63306201 0.89065281 0.43260636 0.92821871 0.59208066]]

 [[0.43178493 0.59278027 0.35450605 0.65701977 0.65230895]
  [0.82171856 0.40276676 0.03756505 0.98463162 0.44814283]
  [0.93763523 0.67204106 0.26669688 0.56406436 0.95693298]
  [0.11348592 0.27222936 0.08205775 0.76527058 0.02168872]]]


In [34]:
s1 = s.reshape(2, 6, 5)
print(f"Reshaped from s: {s1.shape}")

print(s1)

Reshaped from s: (2, 6, 5)
[[[0.10642941 0.31648792 0.24653479 0.56278312 0.90635423]
  [0.58010691 0.59793673 0.23804352 0.58088727 0.14587015]
  [0.33563098 0.62552797 0.36130568 0.91099399 0.87849262]
  [0.43415558 0.5176121  0.47466799 0.1843626  0.43476064]
  [0.18755194 0.71520783 0.52300639 0.32056533 0.00309954]
  [0.59730294 0.64907833 0.00518963 0.9702218  0.66386607]]

 [[0.2931444  0.20036432 0.92570215 0.30925129 0.40321803]
  [0.63306201 0.89065281 0.43260636 0.92821871 0.59208066]
  [0.43178493 0.59278027 0.35450605 0.65701977 0.65230895]
  [0.82171856 0.40276676 0.03756505 0.98463162 0.44814283]
  [0.93763523 0.67204106 0.26669688 0.56406436 0.95693298]
  [0.11348592 0.27222936 0.08205775 0.76527058 0.02168872]]]


#### Reshaping to a different number of dimensions

In [37]:
r = np.arange(120)

print(f"Original shape: {r.shape}")

print(r)

Original shape: (120,)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]


In [39]:
print(r.reshape(3,4,10))

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]


In [40]:
# (120,) -> (3, 4, 10)
r1 = r.reshape(3, 4, 10) # this can also be written as r.reshape((3, 4, 10))
print(f"Reshaped from r: {r1.shape}")

print(r1)

Reshaped from r: (3, 4, 10)
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]


In [41]:
# (3, 4, 10) -> (6, 20)
r2 = r1.reshape(6, 20)
print(f"Reshaped from r1: {r2.shape}")

print(r2)

Reshaped from r1: (6, 20)
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]]


### b. Transposing Arrays
The transpose operation reverses the order of an array. It switches the rows to columns and vice versa. In a multi-dimensional array, the transpose operation moves the data from one axis to another in the order specified in the transpose method.

In [ ]:
x=np.arange(50).reshape((5,10))
print("Shape of the original array", x.shape)
print("Original array\n", x)

x1=np.transpose(x)
print("Shape of the transposed array", x1.shape)
print("Transposed array\n", x1)

x.T

In [42]:
x = np.arange(50).reshape((5,10))
print("Shape of the original array", x.shape)
print("Original array\n", x)

x1 = np.transpose(x)
print("Shape of the transposed array", x1.shape)
print("Transposed array\n",x1)

Shape of the original array (5, 10)
Original array
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Shape of the transposed array (10, 5)
Transposed array
 [[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


In [44]:
w = np.arange(60).reshape((3, 4, 5))
w

print("Shape of the Original array", w.shape)
#print("Original array\n", w)



Shape of the Original array (3, 4, 5)


#### Transpose without specifying axes

In [ ]:
# Original Shape: 3,4,5

w1 = np.transpose(w)  # 0->2, 1->1, 2->0   (0,1,2)->(2,1,0)
print("Shape of the transposed array", w1.shape)
print("Transposed array\n", w1)

#### Transpose along specified axes

In [ ]:
w

# Original Shape: 3,4,5

w2 = np.transpose(w, axes=(0, 2, 1)) # 0, 1, 2
print("Shape of the transposed array", w2.shape)
print("Transposed array\n", w2)

# Original Shape: 3,4,5

w3 = np.transpose(w, axes=(1, 2, 0))
print("Shape of the transposed array", w3.shape)
print("Transposed array\n", w3)

### c. Flattening Arrays
The flatten operation in Numpy collapses arrays of multiple dimensions into one dimension.


Different orders can be specified when flattening Numpy Arrays. See examples below.

In [ ]:
k = np.random.rand(5, 6)

k

#### Flattening Arrays along the row (default order)

In [ ]:
k1 = k.flatten() # all rows are stacked on each other into a 1D array.
k1

k1.shape

#### Flattening Arrays along the column

In [ ]:
k2= k.flatten('F') # forms a 1D array where elements in a column are listed before moving to the next column.
k2

k2.shape

#### Flattening Arrays using Numpy Reshape


In [ ]:
k4= k.reshape(-1)
k4

k4.shape

### d. Squeezing & Expanding Arrays

#### Squeezing Numpy Arrays

The squeeze operation allows reduction of numpy arrays axes by dropping a specified axis, so long as it is of **unit length**. The product of the shape (overall size of the array) remains the same.

In [ ]:
sq = np.random.rand(4, 1, 5)
print(f"Original Array: \n{sq}\n")
print(f"Shape of Original Array: {sq.shape}")

# transforms from (4, 1, 5) -> (4, 5)
sq1 = np.squeeze(sq)
print(f"Squeezed Array: \n {sq1}\n")
print(f"Shape of Squeezed Array: {sq1.shape}")

In [ ]:
# Squeezing specified axes

q2 = np.squeeze(sq, axis=1)
print(f"Specified axis Squeezed Array: \n {q2}\n")
print(f"Shape of Specified axis Squeezed Array: {q2.shape}")

#### Unsqueezing (Expanding) Numpy Arrays
This is the direct opposite of squeezing. A new unit axis is inserted in specified position. Multiple unit axes can be inserted by using a tuple on the axis attribute of the `expand_dims` method.

In [ ]:
y = np.random.rand(4, 5)
print(f"Original Array: \n {y}\n")
print(f"Shape of Original Array: {y.shape}")

# transforms from (4, 5) -> (4, 1, 5)
y1 = np.expand_dims(y, axis=1)
print(f"Expanded Array: \n {y1}\n")
print(f"Shape of Expanded Array: {y1.shape}")

# transforms from (4, 5) -> (1, 4, 1, 5)
y2 = np.expand_dims(y, axis=(0, 2))
print(f"Multi-axes Expanded Array: \n {y2}\n")
print(f"Shape of Multi-axes Expanded Array: {y2.shape}")

## 7. Combining data

### a. Concatenation

A concatenation operation joins a sequence of arrays along an *existing* axis. All arrays must either have the same shape (except in the concatenating dimension) or be empty.

In [ ]:
# Concatenating Numpy Arrays

array1 = np.random.randint(3, size = (3, 2, 2))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 2, 2))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

concatenated_array1 = np.concatenate((array1, array2), axis = 0) 
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

concatenated_array2 = np.concatenate((array1, array2), axis = 1) 
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

concatenated_array3 = np.concatenate((array1, array2), axis = 2) 
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)


### b. Stacking

The stack operation joins a sequence of arrays along a *new* axis. The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis = 0 it will be the first dimension and if axis = -1 it will be the last dimension. All arrays need to be of the same size.  The stacked array has one more dimension than the input arrays.

In [ ]:
# Stacking 1-d Arrays

array1 = np.array([1, 2, 3])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([4, 5, 6])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")


stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 is \n", stacked_array1, " with dimensions ", stacked_array1.shape)

stacked_array2 = np.stack((array1, array2), axis = 1) 
print("Stacked array 2 is \n", stacked_array2, " with dimensions ", stacked_array2.shape)

stacked_array3 = np.stack((array1, array2), axis = -1) 
print("Stacked array 3 is \n", stacked_array3, " with dimensions ", stacked_array3.shape)

In [ ]:

# Stacking Numpy Arrays

array1 = np.random.randint(3, size = (3, 4, 5))
print("Array 1 has dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 4, 5))
print("Array 2 has dimensions ", array2.shape, "\n")

stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 has dimensions", stacked_array1.shape, "\n")

stacked_array2 = np.stack((array1, array2), axis = 1) 
print("Stacked array 2 has dimensions", stacked_array2.shape, "\n")

stacked_array3 = np.stack((array1, array2), axis = 2) 
print("Stacked array 3 has dimensions", stacked_array3.shape, "\n")

stacked_array4 = np.stack((array1, array2), axis = -1)
print("Stacked array 4 has dimensions", stacked_array4.shape, "\n")

### c. Repeat

The repeat operation repeats elements of an array. The number of repetitions for each element is broadcasted to fit the shape of the given axis. The axis parameter specifies along which axis to repeat values. By default, it uses the flattened input array, and returns a flat output array.

In [ ]:

# Repeat in Numpy Arrays

original_array = np.array([[1,2],[3,4]])
print("Array is \n", original_array, " with dimensions ", original_array.shape, "\n")

repeated_array1 = np.repeat(original_array, 2)
print("Repeated array 1 is \n", repeated_array1, "\n\n", "and the dimensions of the repeated array 1 are: \n", repeated_array1.shape, "\n")

repeated_array2 = np.repeat(original_array, 3, axis=0)
print("Repeated array 2 is \n", repeated_array2, "\n\n", "and the dimensions of the repeated array 2 are: \n", repeated_array2.shape, "\n")

repeated_array3 = np.repeat(original_array, 3, axis=1)
print("Repeated array 3 is \n", repeated_array3, "\n\n", "and the dimensions of the repeated array 3 are: \n", repeated_array3.shape, "\n")

repeated_array4 = np.repeat(original_array, [2,3], axis=0)
print("Repeated array 4 is \n", repeated_array4, "\n\n", "and the dimensions of the repeated array 4 are: \n", repeated_array4.shape, "\n")


## 8. Math operations

In this section we will cover some commonly used mathematical operations
1. Broadcasting
1. Point-wise/element-wise operations
1. Reduction operations
1. Comparison operations
1. Vector/Matrix operations
1. Tensordot

### a. Broadcasting

In [ ]:
# Broadcasting b/w arrays of different dimensions
# Note: When broadting two multi-dimensional tensors, match their corresponding dimensions beginning from the last dimension.
# All dimensions should either match or one of the arrays should have length 1 in that specific dimension

row_arr = np.random.rand(1,3)
print("A row array: \n", row_arr, " with dimensions ", row_arr.shape, "\n")
col_arr = np.random.rand(4,1)
print("A column array: \n", col_arr, " with dimensions ", col_arr.shape, "\n")

add_arr = row_arr + col_arr
print("row array + column array = ")
print(add_arr," with dimensions ", add_arr.shape, "\n")
mul_arr = row_arr * col_arr
print("row array * column array = ")
print(mul_arr," with dimensions ", mul_arr.shape, "\n")

### b. Element-wise operations

In [ ]:
rand_arr_1 = np.random.rand(2,3)
print("A random array1 : \n", rand_arr_1, " with dimensions ", rand_arr_1.shape, "\n")
rand_arr_2 = np.random.rand(2,3)
print("A random array2 : \n", rand_arr_2, " with dimensions ", rand_arr_2.shape, "\n")
scalar = 5.0

# Addition with Scalars
new_arr_1 = rand_arr_1 + scalar
print("random array1 + 5.0 =")
print(new_arr_1, "\n")

# Multiplication with Scalars
new_arr_2 = rand_arr_1 * scalar
print("random array1 * 5.0 =")
print(new_arr_2, "\n")

# Elementwise Addition of Arrays
new_arr_3 = rand_arr_1 + rand_arr_2
print("random array1 + random array2 =")
print(new_arr_3, "\n")

# Elementwise Multiplication of Arrays aka Hadmard Product
new_arr_4 = rand_arr_1 * rand_arr_2
print("random array1 * random array2 =")
print(new_arr_4, "\n") # also equivalent to np.multiply(array1, array2)

# Absolute value
new_arr_5 = np.abs(-10*rand_arr_1)
print("abs (-10 * random array1) =")
print(new_arr_5, "\n")

# Square root value
new_arr_6 = np.sqrt(rand_arr_1)
print('sqrt(random array1) = \n', new_arr_6, "\n")

### c. Reduction

In [ ]:
rand_arr = np.random.rand(2,3)
print('random array: \n', rand_arr, "\n")

max_val = np.max(rand_arr)
print('Maximum value of array \n', max_val, "\n")
min_val = np.min(rand_arr)
print('Minimum value of array \n', min_val, "\n")

sum_val = np.sum(rand_arr)
print('Sum of array \n', sum_val, "\n")
max_idx = np.argmax(rand_arr, axis=0)
print('Maximum value\'s index of array along axis 0 \n', max_idx, "\n")
min_idx = np.argmin(rand_arr, axis=1)
print('Minimum value\'s index of array along axis 1 \n', min_idx, "\n")

mean_val = np.mean(rand_arr)
print('Mean value of array \n', mean_val, "\n")
std_val = np.std(rand_arr)
print('Standard deviation value of array \n', std_val, "\n")
norm_val = np.linalg.norm(rand_arr)
print('Norm value of array \n', norm_val, "\n")

### d. Comparision

In [ ]:
rand_arr_1 = np.random.rand(2,3)
print('random array1: \n', rand_arr_1, '\n')
rand_arr_2 = np.random.rand(2,3)
print('random array2: \n', rand_arr_2, '\n')

# Element-wise Comparison Operations
greater_compare = rand_arr_1 > rand_arr_2
print('random array1 > random array2')
print(greater_compare, '\n')

less_compare = rand_arr_1 < rand_arr_2
print('random array1 < random array2')
print(less_compare, '\n')

not_equal_compare = rand_arr_1 != rand_arr_2
print('random array1 != random array2')
print(not_equal_compare, '\n')

# Combining reduction operations with boolean arrays
print("any values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(), "\n")

print("all values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).all(), "\n")

print("any values along first axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=0), "\n")

print("any values along second axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=1), "\n")

print("any values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).any(), "\n")

print("all values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).all(), "\n")

### e. Vector/Matrix operations

In [ ]:
# Vector x Vector
array1 = np.random.randn(3)
array2 = np.random.randn(3)

print('Array1 \n', array1, 'with dimension ', array1.shape, '\n')
print('Array2 \n', array2, 'with dimension ', array2.shape, '\n')

matmul_arr = np.matmul(array1, array2)
another_arr = array1@array2
print('Matmul of the two arrays can be derived by using np.matmul(array1, array2) \n', matmul_arr)
print("Matmul of the two arrays can also be derived by using array1@array2 \n", another_arr)
print('Dimensions of resulting product: \n', matmul_arr.shape)

# Matrix x Vector
array3 = np.random.randn(3, 4)
array4 = np.random.randn(4)

print('Array3 \n', array3, 'with dimension ', array3.shape, '\n')
print('Array4 \n', array4, 'with dimension ', array4.shape, '\n')

matmul_arr = np.matmul(array3, array4)
another_arr = array3@array4
print('Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) \n', matmul_arr)
print('Matmul of a vector and a matrix can also be derived by using array3@array4 \n', another_arr)
print('Dimensions of resulting product: \n', matmul_arr.shape)

# Matrix x Matrix 

matrix1 = np.random.randint(4, size = (2, 3))
matrix2 = np.random.randint(4, size = (3, 2))

print('Matrix1 \n', matrix1, 'with dimension ', matrix1.shape, '\n')
print('Matrix2 \n', matrix2, 'with dimension ', matrix2.shape, '\n')

matmul_mat = np.matmul(matrix1, matrix2)
print('Matmul of two matrices can be derived by using np.matmul(matrix1, matrix2) \n', matmul_mat)
print('Dimensions of resulting product: \n', matmul_mat.shape, "\n")

In [ ]:
rand_mat_1 = np.random.rand(4,2)
rand_mat_2 = np.random.rand(2,3)
print('Matrix1 \n', rand_mat_1, 'with dimension ', rand_mat_1.shape, '\n')
print('Matrix2 \n', rand_mat_2, 'with dimension ', rand_mat_2.shape, '\n')

# dot product
dot_mat = np.dot(rand_mat_1, rand_mat_2)
another_mat = rand_mat_1@rand_mat_2
print('Dot product of two matrices can be derived by using np.dot(mat1, mat2) \n', dot_mat)
print('Dot product of two matrices can also be derived by using mat1@mat2 \n', another_mat)
print('Dimensions of resulting product: \n', dot_mat.shape)

a = np.ones([9, 5, 7, 4])
b = np.ones([9, 5, 4, 3])
print('array1 \'s dimension ', a.shape, '\n')
print('array2 \'s dimension ', b.shape, '\n')

# matmul with multi-dimenstion arrays
c = np.matmul(a,b)
print('Matmul of two multi-dimension arrays can be derived by using np.matmul(array1, array2) \n')
print('Dimensions of resulting product: \n', c.shape)

### f. Tensordot

Understanding tensordot function will help you in writing succint code for your homeworks especially in Convolutional Neural Net assignment.

To give a brief overview: 
We input the arrays and the respective axes along which the sum-reductions are intended. The axes that take part in sum-reduction are removed in the output and all of the remaining axes from the input arrays are spread-out as different axes in the output keeping the order in which the input arrays are fed.

To understand in depth please checkout: https://stackoverflow.com/questions/41870228/understanding-tensordot

In [ ]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
print('A \'s dimension ', a.shape, '\n')
print('B \'s dimension ', b.shape, '\n')

# compute tensor dot product along specified axes.
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print("A⨂B =\n", c, ' with dimension', c.shape, '\n')

# this equals to 
d = np.zeros((5,2))
for i in range(5):
  for j in range(2):
    for k in range(3):
      for n in range(4):
        d[i,j] += a[k,n,i] * b[n,k,j]
print("tensor dot is equal to sum over certain dimensions.\n")
print(c==d)